export interface IconToc {
  color: string;
  colorGradient?: string;
  desc: string;
  docsUrl: string;
  fullTitle: string;
  group: 'model' | 'provider' | 'application';
  id: string;
  param: {
    hasAvatar: boolean;
    hasBrand: boolean;
    hasBrandColor: boolean;
    hasColor: boolean;
    hasCombine: boolean;
    hasText: boolean;
    hasTextCn: boolean;
    hasTextColor: boolean;
  };
  title: string;
}

const toc: IconToc[] = [
  {
    color: '#EB1000',
    desc: 'https://adobe.com',
    docsUrl: 'adobe',
    fullTitle: 'Adobe',
    group: 'application',
    id: 'Adobe',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Adobe',
  },
  {
    color: '#EB1000',
    desc: 'https://firefly.adobe.com',
    docsUrl: 'adobe-firefly',
    fullTitle: 'Firefly (Adobe)',
    group: 'application',
    id: 'AdobeFirefly',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'AdobeFirefly',
  },
  {
    color: '#E91E63',
    colorGradient: 'linear-gradient(-45deg, #F68CB2,  #E91E63)',
    desc: 'https://huggingface.co/ai21labs',
    docsUrl: 'ai21',
    fullTitle: 'Ai21Labs (Jamba)',
    group: 'model',
    id: 'Ai21',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'AI21',
  },
  {
    color: '#006ffb',
    colorGradient: 'linear-gradient(to bottom, #12B7FA,  #006ffb)',
    desc: 'https://ai.360.com/',
    docsUrl: 'ai360',
    fullTitle: 'Ai360 (360智脑)',
    group: 'provider',
    id: 'Ai360',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'AI360',
  },
  {
    color: '#006FFB',
    desc: 'https://aihubmix.com',
    docsUrl: 'ai-hub-mix',
    fullTitle: 'AiHubMix (推理时代)',
    group: 'provider',
    id: 'AiHubMix',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'AiHubMix',
  },
  {
    color: '#fff',
    desc: 'https://ai-maas.wair.ac.cn',
    docsUrl: 'ai-mass',
    fullTitle: 'AiMass (紫东太初)',
    group: 'provider',
    id: 'AiMass',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'AiMass',
  },
  {
    color: '#0057CC',
    desc: 'https://aistudio.google.com',
    docsUrl: 'ai-studio',
    fullTitle: 'AI Studio (Google)',
    group: 'provider',
    id: 'AiStudio',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Google AI Studio',
  },
  {
    color: '#0f172a',
    desc: 'https://aionlabs.ai',
    docsUrl: 'aion-labs',
    fullTitle: 'AionLabs',
    group: 'model',
    id: 'AionLabs',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'AionLabs',
  },
  {
    color: '#fff',
    desc: 'https://aleph-alpha.com',
    docsUrl: 'aleph-alpha',
    fullTitle: 'AlephAlpha',
    group: 'provider',
    id: 'AlephAlpha',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'AlephAlpha',
  },
  {
    color: '#FF6003',
    desc: 'https://alibaba.com',
    docsUrl: 'alibaba',
    fullTitle: 'Alibaba',
    group: 'provider',
    id: 'Alibaba',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: false,
      hasText: true,
      hasTextCn: true,
      hasTextColor: false,
    },
    title: 'Alibaba',
  },
  {
    color: '#FF6A00',
    desc: 'https://aliyun.com',
    docsUrl: 'alibaba-cloud',
    fullTitle: 'AlibabaCloud (阿里云)',
    group: 'provider',
    id: 'AlibabaCloud',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: true,
      hasTextColor: false,
    },
    title: 'AlibabaCloud',
  },
  {
    color: '#1677ff',
    desc: 'https://antgroup.com',
    docsUrl: 'ant-group',
    fullTitle: 'AntGroup',
    group: 'provider',
    id: 'AntGroup',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: false,
      hasText: true,
      hasTextCn: true,
      hasTextColor: false,
    },
    title: 'AntGroup',
  },
  {
    color: '#F1F0E8',
    desc: 'https://anthropic.com',
    docsUrl: 'anthropic',
    fullTitle: 'Anthropic',
    group: 'provider',
    id: 'Anthropic',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: false,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Anthropic',
  },
  {
    color: '#0163FB',
    desc: 'https://anyscale.com',
    docsUrl: 'anyscale',
    fullTitle: 'Anyscale',
    group: 'provider',
    id: 'Anyscale',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Anyscale',
  },
  {
    color: '#2545D3',
    desc: 'https://assemblyai.com',
    docsUrl: 'assembly-ai',
    fullTitle: 'AssemblyAI',
    group: 'model',
    id: 'AssemblyAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'AssemblyAI',
  },
  {
    color: '#E00054',
    desc: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    docsUrl: 'automatic',
    fullTitle: 'Automatic1111 (SD Webui)',
    group: 'application',
    id: 'Automatic',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Automatic',
  },
  {
    color: '#222F3E',
    desc: 'https://aws.amazon.com',
    docsUrl: 'aws',
    fullTitle: 'AWS',
    group: 'provider',
    id: 'Aws',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'AWS',
  },
  {
    color: '#416FDC',
    desc: 'https://cohere.com/research/aya',
    docsUrl: 'aya',
    fullTitle: 'Aya (Cohere)',
    group: 'model',
    id: 'Aya',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Aya',
  },
  {
    color: '#fff',
    desc: 'https://azure.microsoft.com',
    docsUrl: 'azure',
    fullTitle: 'Microsoft Azure',
    group: 'provider',
    id: 'Azure',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Azure',
  },
  {
    color: '#000',
    desc: 'https://ai.azure.com',
    docsUrl: 'azure-ai',
    fullTitle: 'AzureAI',
    group: 'provider',
    id: 'AzureAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'AzureAI',
  },
  {
    color: '#000',
    desc: 'https://baai.ac.cn',
    docsUrl: 'baai',
    fullTitle: 'BAAI (智源研究院)',
    group: 'model',
    id: 'BAAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'BAAI',
  },
  {
    color: '#FF6933',
    colorGradient: 'linear-gradient(-45deg, #FF6933, #FEC13E)',
    desc: 'https://baichuan-ai.com',
    docsUrl: 'baichuan',
    fullTitle: 'Baichuan (百川)',
    group: 'model',
    id: 'Baichuan',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Baichuan',
  },
  {
    color: '#2932E1',
    desc: 'https://baidu.com',
    docsUrl: 'baidu',
    fullTitle: 'Baidu',
    group: 'provider',
    id: 'Baidu',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: false,
      hasText: true,
      hasTextCn: true,
      hasTextColor: false,
    },
    title: 'Baidu',
  },
  {
    color: '#2468f2',
    desc: 'https://cloud.baidu.com',
    docsUrl: 'baidu-cloud',
    fullTitle: 'BaiduCloud (百度智能云)',
    group: 'provider',
    id: 'BaiduCloud',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'BaiduCloud',
  },
  {
    color: '#222F3E',
    colorGradient: 'linear-gradient(45deg, #9AD8F8, #3D8FFF, #6350FB)',
    desc: 'https://aws.amazon.com/bedrock',
    docsUrl: 'bedrock',
    fullTitle: 'Bedrock (AWS)',
    group: 'provider',
    id: 'Bedrock',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Bedrock',
  },
  {
    color: '#174ae4',
    colorGradient: 'linear-gradient(130deg, #2870EA 20%, #1B4AEF 77.5%)',
    desc: 'https://bing.com',
    docsUrl: 'bing',
    fullTitle: 'Microsoft Bing',
    group: 'application',
    id: 'Bing',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Bing',
  },
  {
    color: '#325AB4',
    desc: 'https://bytedance.com',
    docsUrl: 'byte-dance',
    fullTitle: 'ByteDance',
    group: 'provider',
    id: 'ByteDance',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: false,
      hasText: true,
      hasTextCn: true,
      hasTextColor: false,
    },
    title: 'ByteDance',
  },
  {
    color: '#004331',
    desc: 'https://centml.ai',
    docsUrl: 'cent-ml',
    fullTitle: 'CentML',
    group: 'provider',
    id: 'CentML',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'CentML',
  },
  {
    color: '#F15A29',
    desc: 'https://cerebras.ai',
    docsUrl: 'cerebras',
    fullTitle: 'Cerebras',
    group: 'provider',
    id: 'Cerebras',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Cerebras',
  },
  {
    color: '#4268FA',
    colorGradient: 'linear-gradient(-45deg, #3485FF,  #504AF4)',
    desc: 'https://github.com/THUDM/ChatGLM-6B',
    docsUrl: 'chat-glm',
    fullTitle: 'ChatGLM (智谱)',
    group: 'model',
    id: 'ChatGLM',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'ChatGLM',
  },
  {
    color: '#fff',
    desc: 'https://civitai.com',
    docsUrl: 'civitai',
    fullTitle: 'Civitai',
    group: 'provider',
    id: 'Civitai',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Civitai',
  },
  {
    color: '#D97757',
    desc: 'https://claude.ai',
    docsUrl: 'claude',
    fullTitle: 'Claude',
    group: 'model',
    id: 'Claude',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Claude',
  },
  {
    color: '#323B43',
    desc: 'https://cline.bot',
    docsUrl: 'cline',
    fullTitle: 'Cline',
    group: 'application',
    id: 'Cline',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Cline',
  },
  {
    color: '#000',
    desc: 'https://clipdrop.co',
    docsUrl: 'clipdrop',
    fullTitle: 'Clipdrop',
    group: 'application',
    id: 'Clipdrop',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Clipdrop',
  },
  {
    color: '#F38020',
    desc: 'https://cloudflare.com',
    docsUrl: 'cloudflare',
    fullTitle: 'Cloudflare',
    group: 'provider',
    id: 'Cloudflare',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Cloudflare',
  },
  {
    color: '#00e7e7',
    colorGradient: 'linear-gradient(to right, #00E7E7,  #00BFFF)',
    desc: 'https://codegeex.cn/',
    docsUrl: 'code-gee-x',
    fullTitle: 'CodeGeeX',
    group: 'model',
    id: 'CodeGeeX',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'CodeGeeX',
  },
  {
    color: '#000',
    desc: 'https://github.com/THUDM/CogVideo',
    docsUrl: 'cog-video',
    fullTitle: 'CogVideo',
    group: 'model',
    id: 'CogVideo',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'CogVideo',
  },
  {
    color: '#000',
    desc: 'https://github.com/THUDM/CogView3',
    docsUrl: 'cog-view',
    fullTitle: 'CogView',
    group: 'model',
    id: 'CogView',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'CogView',
  },
  {
    color: '#39594D',
    desc: 'https://cohere.com',
    docsUrl: 'cohere',
    fullTitle: 'Cohere',
    group: 'provider',
    id: 'Cohere',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Cohere',
  },
  {
    color: '#F9AB00',
    desc: 'https://colab.research.google.com/',
    docsUrl: 'colab',
    fullTitle: 'Google (Colab)',
    group: 'application',
    id: 'Colab',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Colab',
  },
  {
    color: '#000',
    colorGradient: 'linear-gradient(135deg, #0CD7FE, #03ACFF, #0272E1)',
    desc: 'https://comfy.org',
    docsUrl: 'comfy-ui',
    fullTitle: 'ComfyUI',
    group: 'application',
    id: 'ComfyUI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'ComfyUI',
  },
  {
    color: '#39594D',
    desc: 'https://cohere.com/blog/command',
    docsUrl: 'command-a',
    fullTitle: 'CommandA (Cohere)',
    group: 'model',
    id: 'CommandA',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'CommandA',
  },
  {
    color: '#fff',
    desc: 'https://copilot.microsoft.com',
    docsUrl: 'copilot',
    fullTitle: 'Microsoft Copilot',
    group: 'application',
    id: 'Copilot',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Copilot',
  },
  {
    color: '#03363D',
    desc: 'https://github.com/coqui-ai/TTS',
    docsUrl: 'coqui',
    fullTitle: 'Coqui',
    group: 'application',
    id: 'Coqui',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Coqui',
  },
  {
    color: '#4D53E8',
    desc: 'https://coze.com',
    docsUrl: 'coze',
    fullTitle: 'Coze',
    group: 'application',
    id: 'Coze',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Coze',
  },
  {
    color: '#fff',
    desc: 'https://crewai.com',
    docsUrl: 'crew-ai',
    fullTitle: 'CrewAI',
    group: 'application',
    id: 'CrewAI',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'CrewAI',
  },
  {
    color: '#fff',
    desc: 'https://crusoe.ai',
    docsUrl: 'crusoe',
    fullTitle: 'Crusoe',
    group: 'provider',
    id: 'Crusoe',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Crusoe',
  },
  {
    color: '#000',
    desc: 'https://cursor.com',
    docsUrl: 'cursor',
    fullTitle: 'Cursor',
    group: 'application',
    id: 'Cursor',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Cursor',
  },
  {
    color: '#000',
    colorGradient: 'conic-gradient(from 180deg, #FFFF67, #43FFFF, #50DA4C, #FF6E3D, #3C46FF)',
    desc: 'https://openai.com/dall-e-3',
    docsUrl: 'dalle',
    fullTitle: 'DALL·E (OpenAI)',
    group: 'model',
    id: 'Dalle',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'DALL-E',
  },
  {
    color: '#EE3D2C',
    desc: 'https://databricks.com',
    docsUrl: 'dbrx',
    fullTitle: 'DBRX (Databricks)',
    group: 'model',
    id: 'Dbrx',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'DBRX',
  },
  {
    color: '#fff',
    desc: 'hhttps://deepai.org',
    docsUrl: 'deep-ai',
    fullTitle: 'DeepAI',
    group: 'application',
    id: 'DeepAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'DeepAI',
  },
  {
    color: '#fff',
    desc: 'https://deepinfra.com',
    docsUrl: 'deep-infra',
    fullTitle: 'DeepInfra',
    group: 'provider',
    id: 'DeepInfra',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'DeepInfra',
  },
  {
    color: '#4285F4',
    desc: 'https://deepmind.google',
    docsUrl: 'deep-mind',
    fullTitle: 'DeepMind (Google)',
    group: 'provider',
    id: 'DeepMind',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'DeepMind',
  },
  {
    color: '#4D6BFE',
    desc: 'https://deepseek.com',
    docsUrl: 'deep-seek',
    fullTitle: 'DeepSeek',
    group: 'model',
    id: 'DeepSeek',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'DeepSeek',
  },
  {
    color: '#fff',
    colorGradient: 'conic-gradient(from 180deg at 50% 50%, #0222C3, #8FB1F4, #FFFFFF)',
    desc: 'https://dify.ai',
    docsUrl: 'dify',
    fullTitle: 'Dify',
    group: 'application',
    id: 'Dify',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Dify',
  },
  {
    color: '#fff',
    desc: 'https://doc2x.noedgeai.com',
    docsUrl: 'doc2-x',
    fullTitle: 'Doc2X',
    group: 'application',
    id: 'Doc2X',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Doc2X',
  },
  {
    color: '#fff',
    desc: 'https://docsearch.algolia.com',
    docsUrl: 'doc-search',
    fullTitle: 'DocSearch',
    group: 'application',
    id: 'DocSearch',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'DocSearch',
  },
  {
    color: '#FFF',
    desc: 'https://team.doubao.com',
    docsUrl: 'doubao',
    fullTitle: 'Doubao (豆包)',
    group: 'model',
    id: 'Doubao',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Doubao',
  },
  {
    color: '#000',
    desc: 'https://lumalabs.ai/dream-machine',
    docsUrl: 'dream-machine',
    fullTitle: 'DreamMachine (Luma)',
    group: 'application',
    id: 'DreamMachine',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'DreamMachine',
  },
  {
    color: '#1f40ed',
    desc: 'https://exa.ai',
    docsUrl: 'exa',
    fullTitle: 'Exa',
    group: 'provider',
    id: 'Exa',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Exa',
  },
  {
    color: '#EC0648',
    desc: 'https://fal.ai',
    docsUrl: 'fal',
    fullTitle: 'Fal',
    group: 'provider',
    id: 'Fal',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Fal',
  },
  {
    color: '#fff',
    desc: 'https://tryfastgpt.ai',
    docsUrl: 'fast-gpt',
    fullTitle: 'FastGPT',
    group: 'application',
    id: 'FastGPT',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'FastGPT',
  },
  {
    color: '#FFE184',
    desc: 'https://featherless.ai',
    docsUrl: 'featherless',
    fullTitle: 'Featherless.ai',
    group: 'provider',
    id: 'Featherless',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'featherless.ai',
  },
  {
    color: '#5019C5',
    desc: 'https://fireworks.ai',
    docsUrl: 'fireworks',
    fullTitle: 'Fireworks',
    group: 'provider',
    id: 'Fireworks',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Fireworks',
  },
  {
    color: '#fff',
    desc: 'https://github.com/fishaudio',
    docsUrl: 'fish-audio',
    fullTitle: 'FishAudio (Bert)',
    group: 'model',
    id: 'FishAudio',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'FishAudio',
  },
  {
    color: '#000',
    desc: 'https://florafauna.ai',
    docsUrl: 'flora',
    fullTitle: 'Flora',
    group: 'application',
    id: 'Flora',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Flora',
  },
  {
    color: '#fff',
    desc: 'https://flowith.io',
    docsUrl: 'flowith',
    fullTitle: 'Flowith',
    group: 'application',
    id: 'Flowith',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Flowith',
  },
  {
    color: '#fff',
    desc: 'https://blackforestlabs.ai',
    docsUrl: 'flux',
    fullTitle: 'Flux (black forest labs)',
    group: 'model',
    id: 'Flux',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Flux',
  },
  {
    color: '#101723',
    desc: 'https://friendli.ai',
    docsUrl: 'friendli',
    fullTitle: 'Friendli',
    group: 'provider',
    id: 'Friendli',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Friendli',
  },
  {
    color: '#1C69FF',
    colorGradient: 'linear-gradient(45deg, #1C69FF 40%,  #F0DCD6 100%)',
    desc: 'https://deepmind.google/technologies/gemini',
    docsUrl: 'gemini',
    fullTitle: 'Gemini (Google)',
    group: 'model',
    id: 'Gemini',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Gemini',
  },
  {
    color: '#2E96FF',
    colorGradient: 'linear-gradient(45deg, #446EFF 14%, #2E96FF 40%, #B1C5FF 73%)',
    desc: 'https://ai.google.dev/gemma',
    docsUrl: 'gemma',
    fullTitle: 'Gemma (Google)',
    group: 'model',
    id: 'Gemma',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Gemma',
  },
  {
    color: '#000',
    desc: 'https://ai-assets.gitee.com/',
    docsUrl: 'gitee-ai',
    fullTitle: 'GiteeAI',
    group: 'provider',
    id: 'GiteeAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'GiteeAI',
  },
  {
    color: '#000',
    desc: 'https://github.com',
    docsUrl: 'github',
    fullTitle: 'Github',
    group: 'provider',
    id: 'Github',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Github',
  },
  {
    color: '#000',
    desc: 'https://github.com/features/copilot',
    docsUrl: 'github-copilot',
    fullTitle: 'Github Copilot',
    group: 'application',
    id: 'GithubCopilot',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'GithubCopilot',
  },
  {
    color: '#000',
    desc: 'https://glif.app',
    docsUrl: 'glif',
    fullTitle: 'Glif',
    group: 'application',
    id: 'Glif',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: false,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Glif',
  },
  {
    color: '#fff',
    desc: 'https://google.com',
    docsUrl: 'google',
    fullTitle: 'Google',
    group: 'provider',
    id: 'Google',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: false,
      hasText: false,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Google',
  },
  {
    color: '#fff',
    desc: 'https://block.github.io/goose',
    docsUrl: 'goose',
    fullTitle: 'Goose (codename)',
    group: 'application',
    id: 'Goose',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Goose',
  },
  {
    color: '#fff',
    desc: 'https://gradio.app',
    docsUrl: 'gradio',
    fullTitle: 'Gradio',
    group: 'application',
    id: 'Gradio',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Gradio',
  },
  {
    color: '#44A775',
    desc: 'https://greptile.com',
    docsUrl: 'greptile',
    fullTitle: 'Greptile',
    group: 'application',
    id: 'Greptile',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Greptile',
  },
  {
    color: '#000',
    desc: 'https://grok.x.ai',
    docsUrl: 'grok',
    fullTitle: 'Grok (xAI)',
    group: 'model',
    id: 'Grok',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Grok',
  },
  {
    color: '#F55036',
    desc: 'https://wow.groq.com',
    docsUrl: 'groq',
    fullTitle: 'Groq',
    group: 'provider',
    id: 'Groq',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Groq',
  },
  {
    color: '#fff',
    colorGradient: 'linear-gradient(135deg, #FFAB0C, #FF5538, #E9405D, #D266DA, #D584EF)',
    desc: 'https://hailuoai.video',
    docsUrl: 'hailuo',
    fullTitle: 'Hailuo (海螺)',
    group: 'application',
    id: 'Hailuo',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Hailuo',
  },
  {
    color: '#9581ff',
    desc: 'https://haiper.ai',
    docsUrl: 'haiper',
    fullTitle: 'Haiper',
    group: 'application',
    id: 'Haiper',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Haiper',
  },
  {
    color: '#000',
    desc: 'https://hedra.com',
    docsUrl: 'hedra',
    fullTitle: 'Hedra',
    group: 'application',
    id: 'Hedra',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Hedra',
  },
  {
    color: '#3E5CF4',
    colorGradient: 'linear-gradient(to bottom, #0418FF,  #1E8CFE)',
    desc: 'https://higress.cn/',
    docsUrl: 'higress',
    fullTitle: 'Higress',
    group: 'provider',
    id: 'Higress',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Higress',
  },
  {
    color: '#fff',
    desc: 'https://huggingface.co',
    docsUrl: 'hugging-face',
    fullTitle: 'HuggingFace',
    group: 'provider',
    id: 'HuggingFace',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'HuggingFace',
  },
  {
    color: '#0053e0',
    desc: 'https://hunyuan.tencent.com',
    docsUrl: 'hunyuan',
    fullTitle: 'Hunyuan (腾讯混元)',
    group: 'model',
    id: 'Hunyuan',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Hunyuan',
  },
  {
    color: '#594CE9',
    desc: 'https://hyperbolic.xyz',
    docsUrl: 'hyperbolic',
    fullTitle: 'Hyperbolic',
    group: 'provider',
    id: 'Hyperbolic',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Hyperbolic',
  },
  {
    color: '#2A80E2',
    desc: 'https://xfyun.cn',
    docsUrl: 'i-fly-tek-cloud',
    fullTitle: 'IFlyTekCloud (讯飞开放平台)',
    group: 'provider',
    id: 'IFlyTekCloud',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'iFlyTekCloud',
  },
  {
    color: '#fff',
    desc: 'https://ideogram.ai',
    docsUrl: 'ideogram',
    fullTitle: 'Ideogram',
    group: 'application',
    id: 'Ideogram',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Ideogram',
  },
  {
    color: '#000',
    desc: 'https://inference.net',
    docsUrl: 'inference',
    fullTitle: 'Inference',
    group: 'provider',
    id: 'Inference',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Inference',
  },
  {
    color: '#4334F5',
    desc: 'https://infermatic.ai',
    docsUrl: 'infermatic',
    fullTitle: 'Infermatic',
    group: 'provider',
    id: 'Infermatic',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Infermatic',
  },
  {
    color: '#7952ea',
    desc: 'https://cloud.infini-ai.com',
    docsUrl: 'infinigence',
    fullTitle: 'Infinigence (无问芯穹)',
    group: 'provider',
    id: 'Infinigence',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: true,
      hasTextColor: false,
    },
    title: 'Infinigence',
  },
  {
    color: '#038247',
    desc: 'https://inflection.ai',
    docsUrl: 'inflection',
    fullTitle: 'Inflection',
    group: 'model',
    id: 'Inflection',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Inflection',
  },
  {
    color: '#1B3882',
    desc: 'https://internlm.intern-ai.org.cn',
    docsUrl: 'intern-lm',
    fullTitle: 'InternLM',
    group: 'provider',
    id: 'InternLM',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'InternLM',
  },
  {
    color: '#000',
    desc: 'https://jimeng.jianying.com',
    docsUrl: 'jimeng',
    fullTitle: 'Jimeng (即梦)',
    group: 'application',
    id: 'Jimeng',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Jimeng',
  },
  {
    color: '#000',
    desc: 'https://jina.ai',
    docsUrl: 'jina',
    fullTitle: 'Jina AI',
    group: 'provider',
    id: 'Jina',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: false,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Jina',
  },
  {
    color: '#000',
    desc: 'https://kera.ai',
    docsUrl: 'kera',
    fullTitle: 'Kera',
    group: 'application',
    id: 'Kera',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Kera',
  },
  {
    color: '#000',
    desc: 'https://kimi.moonshot.cn',
    docsUrl: 'kimi',
    fullTitle: 'Kimi',
    group: 'application',
    id: 'Kimi',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Kimi',
  },
  {
    color: '#000',
    colorGradient: 'linear-gradient(45deg, #FFF959, #0DF35E, #0BF2F9, #04A6F0)',
    desc: 'https://klingai.com',
    docsUrl: 'kling',
    fullTitle: 'Kling (可灵)',
    group: 'application',
    id: 'Kling',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Kling',
  },
  {
    color: '#6525F7',
    desc: 'https://kluster.ai',
    docsUrl: 'kluster',
    fullTitle: 'Kluster',
    group: 'provider',
    id: 'Kluster',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Kluster',
  },
  {
    color: '#CB2D30',
    colorGradient: 'linear-gradient(-45deg, #CB2D30, #ED823A)',
    desc: 'https://github.com/haotian-liu/LLaVA',
    docsUrl: 'l-la-va',
    fullTitle: 'LLaVA',
    group: 'model',
    id: 'LLaVA',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'LLaVA',
  },
  {
    color: '#000',
    desc: 'https://lambdalabs.com',
    docsUrl: 'lambda',
    fullTitle: 'Lambda',
    group: 'provider',
    id: 'Lambda',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Lambda',
  },
  {
    color: '#1C3C3C',
    desc: 'https://langchain.com',
    docsUrl: 'lang-chain',
    fullTitle: 'LangChain',
    group: 'application',
    id: 'LangChain',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'LangChain',
  },
  {
    color: '#1C3C3C',
    desc: 'https://langchain.com/LangGraph',
    docsUrl: 'lang-graph',
    fullTitle: 'LangGraph (LangChain)',
    group: 'application',
    id: 'LangGraph',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'LangGraph',
  },
  {
    color: '#1C3C3C',
    desc: 'https://langchain.com/langsmith',
    docsUrl: 'lang-smith',
    fullTitle: 'LangSmith (LangChain)',
    group: 'application',
    id: 'LangSmith',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'LangSmith',
  },
  {
    color: '#000',
    desc: 'https://langfuse.com',
    docsUrl: 'langfuse',
    fullTitle: 'Langfuse',
    group: 'application',
    id: 'Langfuse',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Langfuse',
  },
  {
    color: '#2F80ED',
    desc: 'https://lepton.ai',
    docsUrl: 'lepton-ai',
    fullTitle: 'LeptonAI',
    group: 'provider',
    id: 'LeptonAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'LeptonAI',
  },
  {
    color: '#000',
    desc: 'https://lightricks.com',
    docsUrl: 'lightricks',
    fullTitle: 'Lightricks',
    group: 'application',
    id: 'Lightricks',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Lightricks',
  },
  {
    color: '#fff',
    desc: 'https://liquid.ai',
    docsUrl: 'liquid',
    fullTitle: 'Liquid',
    group: 'model',
    id: 'Liquid',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Liquid',
  },
  {
    color: '#000',
    desc: 'https://livekit.io',
    docsUrl: 'live-kit',
    fullTitle: 'LiveKit',
    group: 'application',
    id: 'LiveKit',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'LiveKit',
  },
  {
    color: '#000',
    desc: 'https://llamaindex.ai',
    docsUrl: 'llama-index',
    fullTitle: 'LlamaIndex',
    group: 'application',
    id: 'LlamaIndex',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'LlamaIndex',
  },
  {
    color: '#4338CA',
    colorGradient: 'linear-gradient(135deg, #6C78EF, #4F14BE)',
    desc: 'https://lmstudio.ai',
    docsUrl: 'lm-studio',
    fullTitle: 'LM Studio',
    group: 'provider',
    id: 'LmStudio',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'LM Studio',
  },
  {
    color: '#fff',
    desc: 'https://lobehub.com',
    docsUrl: 'lobe-hub',
    fullTitle: 'LobeHub',
    group: 'provider',
    id: 'LobeHub',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'LobeHub',
  },
  {
    color: '#000',
    desc: 'https://lumalabs.ai',
    docsUrl: 'luma',
    fullTitle: 'Luma',
    group: 'application',
    id: 'Luma',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Luma',
  },
  {
    color: '#FFF',
    desc: 'https://modelcontextprotocol.io',
    docsUrl: 'mcp',
    fullTitle: 'MCP (Model Context Protocol)',
    group: 'application',
    id: 'MCP',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'ModelContextProtocol',
  },
  {
    color: '#fff',
    desc: 'https://magic.dev',
    docsUrl: 'magic',
    fullTitle: 'Magic',
    group: 'model',
    id: 'Magic',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Magic',
  },
  {
    color: '#ff009a',
    desc: 'https://make.com',
    docsUrl: 'make',
    fullTitle: 'Make',
    group: 'application',
    id: 'Make',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Make',
  },
  {
    color: '#fff',
    desc: 'https://manus.im',
    docsUrl: 'manus',
    fullTitle: 'Manus',
    group: 'application',
    id: 'Manus',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Manus',
  },
  {
    color: '#1d65c1',
    colorGradient: 'linear-gradient(45deg, #007FF8, #0668E1, #007FF8)',
    desc: 'https://llama.meta.com',
    docsUrl: 'meta',
    fullTitle: 'Meta',
    group: 'provider',
    id: 'Meta',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Meta',
  },
  {
    color: '#000',
    desc: 'https://meta.ai',
    docsUrl: 'meta-ai',
    fullTitle: 'MetaAI',
    group: 'application',
    id: 'MetaAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'MetaAI',
  },
  {
    color: '#000',
    desc: 'https://github.com/FoundationAgents/MetaGPT',
    docsUrl: 'meta-gpt',
    fullTitle: 'MetaGPT',
    group: 'application',
    id: 'MetaGPT',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'MetaGPT',
  },
  {
    color: '#00A4EF',
    desc: 'https://microsoft.com',
    docsUrl: 'microsoft',
    fullTitle: 'Microsoft',
    group: 'provider',
    id: 'Microsoft',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Azure',
  },
  {
    color: '#fff',
    desc: 'https://midjourney.com',
    docsUrl: 'midjourney',
    fullTitle: 'Midjourney',
    group: 'application',
    id: 'Midjourney',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Midjourney',
  },
  {
    color: '#F23F5D',
    colorGradient: 'linear-gradient(to right, #E2167E,  #FE603C)',
    desc: 'https://api.minimax.chat',
    docsUrl: 'minimax',
    fullTitle: 'Minimax',
    group: 'model',
    id: 'Minimax',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Minimax',
  },
  {
    color: '#FA520F',
    desc: 'https://mistral.ai',
    docsUrl: 'mistral',
    fullTitle: 'Mistral',
    group: 'model',
    id: 'Mistral',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Mistral',
  },
  {
    color: '#624AFF',
    desc: 'https://modelscope.cn',
    docsUrl: 'model-scope',
    fullTitle: 'ModelScope (魔搭)',
    group: 'provider',
    id: 'ModelScope',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'ModelScope',
  },
  {
    color: '#6841ea',
    colorGradient: 'linear-gradient(90deg, #A83FE0, #515FFB, #2BB5DD)',
    desc: 'https://monica.im',
    docsUrl: 'monica',
    fullTitle: 'Monica',
    group: 'application',
    id: 'Monica',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Monica',
  },
  {
    color: '#16191E',
    desc: 'https://moonshot.cn',
    docsUrl: 'moonshot',
    fullTitle: 'Moonshot (月之暗面)',
    group: 'provider',
    id: 'Moonshot',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'MoonshotAI',
  },
  {
    color: '#fff',
    desc: 'https://myshell.ai',
    docsUrl: 'my-shell',
    fullTitle: 'MyShell',
    group: 'application',
    id: 'MyShell',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'MyShell',
  },
  {
    color: '#EA4B71',
    desc: 'https://n8n.io',
    docsUrl: 'n-8-n',
    fullTitle: 'n8n',
    group: 'application',
    id: 'N8n',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'n8n',
  },
  {
    color: '#00D1B2',
    desc: 'https://nlpcloud.com',
    docsUrl: 'npl-cloud',
    fullTitle: 'NPLCloud',
    group: 'provider',
    id: 'NPLCloud',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'NPLCloud',
  },
  {
    color: '#DAFF33',
    desc: 'https://nebius.com',
    docsUrl: 'nebius',
    fullTitle: 'Nebius',
    group: 'provider',
    id: 'Nebius',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: false,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Nebius',
  },
  {
    color: '#fff',
    desc: 'https://notebooklm.google',
    docsUrl: 'notebook-lm',
    fullTitle: 'NotebookLM',
    group: 'application',
    id: 'NotebookLM',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'NotebookLM',
  },
  {
    color: '#fff',
    desc: 'https://notion.com',
    docsUrl: 'notion',
    fullTitle: 'Notion',
    group: 'application',
    id: 'Notion',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Notion',
  },
  {
    color: '#222F3E',
    colorGradient: 'linear-gradient(135deg, #43E3E4, #4A9FFF, #AA4BFB, #FC5978, #FF6D32)',
    desc: 'https://aws.amazon.com/cn/ai/generative-ai/nova',
    docsUrl: 'nova',
    fullTitle: 'Nova (AWS)',
    group: 'model',
    id: 'Nova',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Nova',
  },
  {
    color: '#23D57C',
    desc: 'https://novita.ai/',
    docsUrl: 'novita',
    fullTitle: 'Novita',
    group: 'provider',
    id: 'Novita',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Novita AI',
  },
  {
    color: '#74B71B',
    desc: 'https://nvidia.com/en-us/ai-on-rtx/chat-with-rtx-generative-ai/',
    docsUrl: 'nvidia',
    fullTitle: 'Nvidia (ChatWithRTX)',
    group: 'application',
    id: 'Nvidia',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Nvidia',
  },
  {
    color: '#fff',
    desc: 'https://ollama.ai',
    docsUrl: 'ollama',
    fullTitle: 'Ollama',
    group: 'provider',
    id: 'Ollama',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Ollama',
  },
  {
    color: '#000',
    desc: 'https://openai.com',
    docsUrl: 'open-ai',
    fullTitle: 'OpenAI (ChatGPT)',
    group: 'provider',
    id: 'OpenAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'OpenAI',
  },
  {
    color: '#4A7FE3',
    desc: 'https://huggingface.co/openchat',
    docsUrl: 'open-chat',
    fullTitle: 'OpenChat',
    group: 'model',
    id: 'OpenChat',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'OpenChat',
  },
  {
    color: '#6566F1',
    desc: 'https://openrouter.ai',
    docsUrl: 'open-router',
    fullTitle: 'OpenRouter',
    group: 'provider',
    id: 'OpenRouter',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'OpenRouter',
  },
  {
    color: '#fff',
    desc: 'https://openwebui.com',
    docsUrl: 'open-web-ui',
    fullTitle: 'OpenWebUI',
    group: 'application',
    id: 'OpenWebUI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'OpenWebUI',
  },
  {
    color: '#2874ff',
    desc: 'https://ppinfra.com',
    docsUrl: 'ppio',
    fullTitle: 'PPIO',
    group: 'provider',
    id: 'PPIO',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: true,
      hasTextColor: false,
    },
    title: 'PPIO',
  },
  {
    color: '#FFF',
    desc: 'https://ai.google/discover/palm2',
    docsUrl: 'pa-lm',
    fullTitle: 'PaLM (Google)',
    group: 'model',
    id: 'PaLM',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'PaLM',
  },
  {
    color: '#000',
    desc: 'https://parasail.io/',
    docsUrl: 'parasail',
    fullTitle: 'Parasail',
    group: 'provider',
    id: 'Parasail',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Parasail',
  },
  {
    color: '#22B8CD',
    desc: 'https://perplexity.ai',
    docsUrl: 'perplexity',
    fullTitle: 'Perplexity',
    group: 'provider',
    id: 'Perplexity',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Perplexity',
  },
  {
    color: '#FF4017',
    desc: 'https://phidata.com',
    docsUrl: 'phidata',
    fullTitle: 'Phidata',
    group: 'application',
    id: 'Phidata',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Phidata',
  },
  {
    color: '#FDF7EF',
    desc: 'https://pika.art',
    docsUrl: 'pika',
    fullTitle: 'Pika',
    group: 'application',
    id: 'Pika',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Pika',
  },
  {
    color: '#9727ef',
    colorGradient: 'linear-gradient(45deg, #3961f1, #9727ef, #ff601a)',
    desc: 'https://app.pixverse.ai',
    docsUrl: 'pix-verse',
    fullTitle: 'PixVerse',
    group: 'application',
    id: 'PixVerse',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'PixVerse',
  },
  {
    color: '#000',
    desc: 'https://poe.com',
    docsUrl: 'poe',
    fullTitle: 'Poe',
    group: 'application',
    id: 'Poe',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Poe',
  },
  {
    color: '#000',
    desc: 'https://pollinations.ai',
    docsUrl: 'pollinations',
    fullTitle: 'Pollinations',
    group: 'application',
    id: 'Pollinations',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Pollinations',
  },
  {
    color: '#E92063',
    desc: 'https://ai.pydantic.dev',
    docsUrl: 'pydantic-ai',
    fullTitle: 'PydanticAI',
    group: 'application',
    id: 'PydanticAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'PydanticAI',
  },
  {
    color: '#1041F3',
    desc: 'https://chatglm.cn',
    docsUrl: 'qingyan',
    fullTitle: 'Qingyan (智谱清言)',
    group: 'application',
    id: 'Qingyan',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Qingyan',
  },
  {
    color: '#06AEEF',
    desc: 'https://qiniu.com',
    docsUrl: 'qiniu',
    fullTitle: 'Qiniu (七牛云)',
    group: 'provider',
    id: 'Qiniu',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Qiniu',
  },
  {
    color: '#615ced',
    colorGradient: 'linear-gradient(to right, #00055F,  #6F69F7)',
    desc: 'https://huggingface.co/Qwen',
    docsUrl: 'qwen',
    fullTitle: 'Qwen (千问)',
    group: 'model',
    id: 'Qwen',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Qwen',
  },
  {
    color: '#fff',
    desc: 'https://rsshub.app',
    docsUrl: 'rss-hub',
    fullTitle: 'RSSHub',
    group: 'application',
    id: 'RSSHub',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'RSSHub',
  },
  {
    color: '#853bce',
    colorGradient: 'linear-gradient(to bottom, #A204B4, #6213B9)',
    desc: 'https://railway.com',
    docsUrl: 'railway',
    fullTitle: 'Railway',
    group: 'application',
    id: 'Railway',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Railway',
  },
  {
    color: '#000',
    desc: 'https://recraft.ai',
    docsUrl: 'recraft',
    fullTitle: 'Recraft',
    group: 'application',
    id: 'Recraft',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Recraft',
  },
  {
    color: '#EA2805',
    desc: 'https://replicate.com',
    docsUrl: 'replicate',
    fullTitle: 'Replicate',
    group: 'provider',
    id: 'Replicate',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: false,
      hasText: false,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Replicate',
  },
  {
    color: '#FD5402',
    desc: 'https://replit.com',
    docsUrl: 'replit',
    fullTitle: 'Replit',
    group: 'application',
    id: 'Replit',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Replit',
  },
  {
    color: '#fff',
    desc: 'https://runwayml.com',
    docsUrl: 'runway',
    fullTitle: 'Runway',
    group: 'application',
    id: 'Runway',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Runway',
  },
  {
    color: '#3431C3',
    desc: 'https://github.com/RWKV',
    docsUrl: 'rwkv',
    fullTitle: 'RWKV',
    group: 'model',
    id: 'Rwkv',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'RWKV',
  },
  {
    color: '#EE7624',
    desc: 'https://sambanova.ai',
    docsUrl: 'samba-nova',
    fullTitle: 'SambaNova',
    group: 'provider',
    id: 'SambaNova',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'SambaNova',
  },
  {
    color: '#0066FF',
    desc: 'https://search1api.com',
    docsUrl: 'search1-api',
    fullTitle: 'Search1API',
    group: 'provider',
    id: 'Search1API',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Search1API',
  },
  {
    color: '#4f46e5',
    desc: 'https://searchapi.io',
    docsUrl: 'search-api',
    fullTitle: 'SearchApi',
    group: 'provider',
    id: 'SearchApi',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'SearchApi',
  },
  {
    color: '#5B2AD8',
    desc: 'https://platform.sensenova.cn',
    docsUrl: 'sense-nova',
    fullTitle: 'SenseNova (商汤)',
    group: 'model',
    id: 'SenseNova',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'SenseNova',
  },
  {
    color: '#7C3AED',
    desc: 'https://siliconflow.cn/zh-cn/',
    docsUrl: 'silicon-cloud',
    fullTitle: 'SiliconCloud (SiliconFlow)',
    group: 'provider',
    id: 'SiliconCloud',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'SiliconCloud',
  },
  {
    color: '#249EDC',
    desc: 'https://snowflake.com',
    docsUrl: 'snowflake',
    fullTitle: 'Snowflake',
    group: 'provider',
    id: 'Snowflake',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Snowflake',
  },
  {
    color: '#0070f0',
    desc: 'https://xinghuo.xfyun.cn',
    docsUrl: 'spark',
    fullTitle: 'Spark (讯飞星火)',
    group: 'model',
    id: 'Spark',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Spark',
  },
  {
    color: '#330066',
    colorGradient: 'linear-gradient(to bottom, #9D39FF,  #A380FF)',
    desc: 'https://deepmind.google/technologies/gemini',
    docsUrl: 'stability',
    fullTitle: 'Stability (StableDiffusion)',
    group: 'provider',
    id: 'Stability',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Stability',
  },
  {
    color: '#DF0428',
    desc: 'https://ctyun.cn/act/xirang/deepseek',
    docsUrl: 'state-cloud',
    fullTitle: 'StateCloud (天翼云)',
    group: 'provider',
    id: 'StateCloud',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'StateCloud',
  },
  {
    color: '#005AFF',
    desc: 'https://stepfun.com',
    docsUrl: 'stepfun',
    fullTitle: 'Stepfun (阶跃星辰)',
    group: 'model',
    id: 'Stepfun',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Stepfun',
  },
  {
    color: '#000',
    desc: 'https://app.suno.ai',
    docsUrl: 'suno',
    fullTitle: 'Suno',
    group: 'application',
    id: 'Suno',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Suno',
  },
  {
    color: '#0000FF',
    desc: 'https://sync.so',
    docsUrl: 'sync',
    fullTitle: 'Sync',
    group: 'application',
    id: 'Sync',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Sync',
  },
  {
    color: '#6400FF',
    desc: 'https://tii.ae',
    docsUrl: 'tii',
    fullTitle: 'Technology Innovation Institute (Falcon)',
    group: 'provider',
    id: 'TII',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Technology Innovation Institute',
  },
  {
    color: '#68C3FF',
    desc: 'https://targon.com',
    docsUrl: 'targon',
    fullTitle: 'Targon',
    group: 'provider',
    id: 'Targon',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Targon',
  },
  {
    color: '#0052D9',
    desc: 'https://tencent.com',
    docsUrl: 'tencent',
    fullTitle: 'Tencent',
    group: 'provider',
    id: 'Tencent',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: false,
      hasText: true,
      hasTextCn: true,
      hasTextColor: false,
    },
    title: 'Tencent',
  },
  {
    color: '#2151d1',
    desc: 'https://cloud.tencent.com',
    docsUrl: 'tencent-cloud',
    fullTitle: 'TencentCloud (腾讯云)',
    group: 'provider',
    id: 'TencentCloud',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'TencentCloud',
  },
  {
    color: '#0057ff',
    colorGradient: 'linear-gradient(to right, #6865FC, #467DF9)',
    desc: 'https://tiangong.cn',
    docsUrl: 'tiangong',
    fullTitle: 'Tiangong (天工)',
    group: 'application',
    id: 'Tiangong',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Tiangong',
  },
  {
    color: '#0f6fff',
    desc: 'https://together.ai',
    docsUrl: 'together',
    fullTitle: 'together.ai',
    group: 'provider',
    id: 'Together',
    param: {
      hasAvatar: true,
      hasBrand: true,
      hasBrandColor: true,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'together.ai',
  },
  {
    color: '#000',
    desc: 'https://topazlabs.com',
    docsUrl: 'topaz-labs',
    fullTitle: 'TopazLabs',
    group: 'application',
    id: 'TopazLabs',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'TopazLabs',
  },
  {
    color: '#000',
    desc: 'https://tripo3d.ai',
    docsUrl: 'tripo',
    fullTitle: 'Tripo',
    group: 'application',
    id: 'Tripo',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Tripo',
  },
  {
    color: '#e30a5d',
    desc: 'https://udio.com',
    docsUrl: 'udio',
    fullTitle: 'Udio',
    group: 'application',
    id: 'Udio',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: false,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Udio',
  },
  {
    color: '#0ADDF8',
    desc: 'https://unstructured.io',
    docsUrl: 'unstructured',
    fullTitle: 'Unstructured',
    group: 'application',
    id: 'Unstructured',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Unstructured',
  },
  {
    color: '#908AF9',
    colorGradient: 'linear-gradient(to bottom, #AEBCFE,  #805DFA)',
    desc: 'https://upstage.ai',
    docsUrl: 'upstage',
    fullTitle: 'Upstage',
    group: 'provider',
    id: 'Upstage',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Upsate',
  },
  {
    color: '#000',
    desc: 'https://v0.dev',
    docsUrl: 'v-0',
    fullTitle: 'V0 (Vercel)',
    group: 'application',
    id: 'V0',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: false,
      hasText: false,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'V0',
  },
  {
    color: '#3659FF',
    desc: 'https://vectorizer.ai',
    docsUrl: 'vectorizer-ai',
    fullTitle: 'Vectorizer.AI',
    group: 'application',
    id: 'VectorizerAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Vectorizer.AI',
  },
  {
    color: '#000',
    desc: 'https://sdk.vercel.ai',
    docsUrl: 'vercel',
    fullTitle: 'Vercel',
    group: 'provider',
    id: 'Vercel',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Vercel',
  },
  {
    color: '#4285F4',
    desc: 'https://cloud.google.com/generative-ai-studio',
    docsUrl: 'vertex-ai',
    fullTitle: 'VertexAI (Google)',
    group: 'provider',
    id: 'VertexAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'VertexAI',
  },
  {
    color: '#22D5FF',
    colorGradient: 'linear-gradient(to right, #40EDD8, #22D5FF, #047FFE)',
    desc: 'https://vidu.com',
    docsUrl: 'vidu',
    fullTitle: 'Vidu',
    group: 'application',
    id: 'Vidu',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Vidu',
  },
  {
    color: '#000',
    desc: 'https://viggle.ai',
    docsUrl: 'viggle',
    fullTitle: 'Viggle',
    group: 'application',
    id: 'Viggle',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Viggle',
  },
  {
    color: '#fff',
    desc: 'https://github.com/vllm-project',
    docsUrl: 'vllm',
    fullTitle: 'vLLM',
    group: 'provider',
    id: 'Vllm',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'vLLM',
  },
  {
    color: '#fff',
    desc: 'https://volcengine.com',
    docsUrl: 'volcengine',
    fullTitle: 'Volcengine (火山引擎)',
    group: 'provider',
    id: 'Volcengine',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Volcengine',
  },
  {
    color: '#012E33',
    desc: 'https://voyageai.com',
    docsUrl: 'voyage',
    fullTitle: 'Voyage',
    group: 'model',
    id: 'Voyage',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: false,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Voyage',
  },
  {
    color: '#167ADF',
    colorGradient: 'linear-gradient(to right, #0A51C3,  #23A4FB)',
    desc: 'https://yiyan.baidu.com',
    docsUrl: 'wenxin',
    fullTitle: 'Wenxin (文心)',
    group: 'model',
    id: 'Wenxin',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Wenxin',
  },
  {
    color: '#F38020',
    desc: 'https://developers.cloudflare.com/workers-ai',
    docsUrl: 'workers-ai',
    fullTitle: 'WorkersAI (Cloudflare)',
    group: 'provider',
    id: 'WorkersAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'WorkersAI',
  },
  {
    color: '#fff',
    desc: 'https://x.ai',
    docsUrl: 'xai',
    fullTitle: 'xAI',
    group: 'provider',
    id: 'XAI',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Grok',
  },
  {
    color: '#781ff5',
    desc: 'https://github.com/xorbitsai/inference',
    docsUrl: 'xinference',
    fullTitle: 'Xinference',
    group: 'provider',
    id: 'Xinference',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Xinference',
  },
  {
    color: '#fff',
    desc: 'https://github.com/Duxiaoman-DI/XuanYuan',
    docsUrl: 'xuanyuan',
    fullTitle: 'Xuanyuan (度小满轩辕)',
    group: 'model',
    id: 'Xuanyuan',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: '轩辕',
  },
  {
    color: '#FB3E1C',
    desc: 'https://ai.yandex.com',
    docsUrl: 'yandex',
    fullTitle: 'Yandex',
    group: 'provider',
    id: 'Yandex',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Yandex',
  },
  {
    color: '#003425',
    desc: 'https://github.com/01-ai/Yi',
    docsUrl: 'yi',
    fullTitle: 'Yi (零一万物)',
    group: 'model',
    id: 'Yi',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Yi',
  },
  {
    color: '#fff',
    desc: 'https://yuanbao.tencent.com',
    docsUrl: 'yuanbao',
    fullTitle: 'Yuanbao (腾讯元宝)',
    group: 'application',
    id: 'Yuanbao',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Yuanbao',
  },
  {
    color: '#FF4F00',
    desc: 'https://zapier.com',
    docsUrl: 'zapier',
    fullTitle: 'Zapier',
    group: 'application',
    id: 'Zapier',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Zapier',
  },
  {
    color: '#6300FF',
    desc: 'https://zeabur.com',
    docsUrl: 'zeabur',
    fullTitle: 'Zeabur',
    group: 'application',
    id: 'Zeabur',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Zeabur',
  },
  {
    color: '#003425',
    desc: 'https://lingyiwanwu.com/',
    docsUrl: 'zero-one',
    fullTitle: '01.AI (零一万物)',
    group: 'provider',
    id: 'ZeroOne',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: false,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: '01.AI',
  },
  {
    color: '#3859FF',
    desc: 'https://zhipuai.cn',
    docsUrl: 'zhipu',
    fullTitle: 'Zhipu (智谱)',
    group: 'provider',
    id: 'Zhipu',
    param: {
      hasAvatar: true,
      hasBrand: false,
      hasBrandColor: false,
      hasColor: true,
      hasCombine: true,
      hasText: true,
      hasTextCn: false,
      hasTextColor: false,
    },
    title: 'Zhipu',
  },
];

export default toc;
