export interface IconToc {
  color: string;
  desc: string;
  docsUrl: string;
  fullTitle: string;
  group: 'model' | 'provider' | 'application';
  id: string;
  title: string;
}

const toc: IconToc[] = [
  {
    color: '#EB1000',
    desc: 'https://adobe.com',
    docsUrl: 'adobe',
    fullTitle: 'Adobe',
    group: 'application',
    id: 'Adobe',
    title: 'Adobe',
  },
  {
    color: '#EB1000',
    desc: 'https://firefly.adobe.com',
    docsUrl: 'adobe-firefly',
    fullTitle: 'Firefly (Adobe)',
    group: 'application',
    id: 'AdobeFirefly',
    title: 'AdobeFirefly',
  },
  {
    color: '#E91E63',
    desc: 'https://huggingface.co/ai21labs',
    docsUrl: 'ai21',
    fullTitle: 'Ai21Labs (Jamba)',
    group: 'model',
    id: 'Ai21',
    title: 'AI21',
  },
  {
    color: '#006ffb',
    desc: 'https://ai.360.com/',
    docsUrl: 'ai360',
    fullTitle: 'Ai360 (360智脑)',
    group: 'provider',
    id: 'Ai360',
    title: 'AI360',
  },
  {
    color: '#fff',
    desc: 'https://ai-maas.wair.ac.cn',
    docsUrl: 'ai-mass',
    fullTitle: 'AiMass (紫东太初)',
    group: 'provider',
    id: 'AiMass',
    title: 'AiMass',
  },
  {
    color: '#FF6003',
    desc: 'https://alibaba.com',
    docsUrl: 'alibaba',
    fullTitle: 'Alibaba',
    group: 'provider',
    id: 'Alibaba',
    title: 'Alibaba',
  },
  {
    color: '#1677ff',
    desc: 'https://antgroup.com',
    docsUrl: 'ant-group',
    fullTitle: 'AntGroup',
    group: 'provider',
    id: 'AntGroup',
    title: 'AntGroup',
  },
  {
    color: '#F1F0E8',
    desc: 'https://anthropic.com',
    docsUrl: 'anthropic',
    fullTitle: 'Anthropic',
    group: 'provider',
    id: 'Anthropic',
    title: 'Anthropic',
  },
  {
    color: '#E00054',
    desc: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    docsUrl: 'automatic',
    fullTitle: 'Automatic1111 (SD Webui)',
    group: 'application',
    id: 'Automatic',
    title: 'Automatic',
  },
  {
    color: '#222F3E',
    desc: 'https://aws.amazon.com',
    docsUrl: 'aws',
    fullTitle: 'AWS',
    group: 'provider',
    id: 'Aws',
    title: 'AWS',
  },
  {
    color: '#416FDC',
    desc: 'https://cohere.com/research/aya',
    docsUrl: 'aya',
    fullTitle: 'Aya (Cohere)',
    group: 'model',
    id: 'Aya',
    title: 'Aya',
  },
  {
    color: '#00A4EF',
    desc: 'https://azure.microsoft.com',
    docsUrl: 'azure',
    fullTitle: 'Microsoft (Azure)',
    group: 'provider',
    id: 'Azure',
    title: 'Azure',
  },
  {
    color: '#FF6933',
    desc: 'https://baichuan-ai.com',
    docsUrl: 'baichuan',
    fullTitle: 'Baichuan (百川)',
    group: 'model',
    id: 'Baichuan',
    title: 'Baichuan',
  },
  {
    color: '#2932E1',
    desc: 'https://baidu.com',
    docsUrl: 'baidu',
    fullTitle: 'Baidu',
    group: 'provider',
    id: 'Baidu',
    title: 'Baidu',
  },
  {
    color: '#2468f2',
    desc: 'https://cloud.baidu.com',
    docsUrl: 'baidu-cloud',
    fullTitle: 'BaiduCloud (百度智能云)',
    group: 'provider',
    id: 'BaiduCloud',
    title: 'BaiduCloud',
  },
  {
    color: '#222F3E',
    desc: 'https://aws.amazon.com/bedrock',
    docsUrl: 'bedrock',
    fullTitle: 'Bedrock (AWS)',
    group: 'provider',
    id: 'Bedrock',
    title: 'Bedrock',
  },
  {
    color: '#174ae4',
    desc: 'https://bing.com',
    docsUrl: 'bing',
    fullTitle: 'Microsoft Bing',
    group: 'application',
    id: 'Bing',
    title: 'Bing',
  },
  {
    color: '#325AB4',
    desc: 'https://bytedance.com',
    docsUrl: 'byte-dance',
    fullTitle: 'ByteDance',
    group: 'provider',
    id: 'ByteDance',
    title: 'ByteDance',
  },
  {
    color: '#4268FA',
    desc: 'https://github.com/THUDM/ChatGLM-6B',
    docsUrl: 'chat-glm',
    fullTitle: 'ChatGLM (智谱)',
    group: 'model',
    id: 'ChatGLM',
    title: 'ChatGLM',
  },
  {
    color: '#D97757',
    desc: 'https://claude.ai',
    docsUrl: 'claude',
    fullTitle: 'Claude',
    group: 'model',
    id: 'Claude',
    title: 'Claude',
  },
  {
    color: '#F38020',
    desc: 'https://cloudflare.com',
    docsUrl: 'cloudflare',
    fullTitle: 'Cloudflare',
    group: 'provider',
    id: 'Cloudflare',
    title: 'Cloudflare',
  },
  {
    color: '#00e7e7',
    desc: 'https://codegeex.cn/',
    docsUrl: 'code-gee-x',
    fullTitle: 'CodeGeeX',
    group: 'model',
    id: 'CodeGeeX',
    title: 'CodeGeeX',
  },
  {
    color: '#000',
    desc: 'https://github.com/THUDM/CogVideo',
    docsUrl: 'cog-video',
    fullTitle: 'CogVideo',
    group: 'model',
    id: 'CogVideo',
    title: 'CogVideo',
  },
  {
    color: '#000',
    desc: 'https://github.com/THUDM/CogView3',
    docsUrl: 'cog-view',
    fullTitle: 'CogView',
    group: 'model',
    id: 'CogView',
    title: 'CogView',
  },
  {
    color: '#39594D',
    desc: 'https://cohere.com',
    docsUrl: 'cohere',
    fullTitle: 'Cohere (Command)',
    group: 'provider',
    id: 'Cohere',
    title: 'Cohere',
  },
  {
    color: '#F9AB00',
    desc: 'https://colab.research.google.com/',
    docsUrl: 'colab',
    fullTitle: 'Google (Colab)',
    group: 'application',
    id: 'Colab',
    title: 'Colab',
  },
  {
    color: '#fff',
    desc: 'https://copilot.microsoft.com',
    docsUrl: 'copilot',
    fullTitle: 'Microsoft Copilot',
    group: 'application',
    id: 'Copilot',
    title: 'Copilot',
  },
  {
    color: '#000',
    desc: 'https://openai.com/dall-e-3',
    docsUrl: 'dalle',
    fullTitle: 'DALL·E (OpenAI)',
    group: 'model',
    id: 'Dalle',
    title: 'DALL-E',
  },
  {
    color: '#EE3D2C',
    desc: 'https://www.databricks.com',
    docsUrl: 'dbrx',
    fullTitle: 'DBRX (Databricks)',
    group: 'model',
    id: 'Dbrx',
    title: 'DBRX',
  },
  {
    color: '#4285F4',
    desc: 'https://deepmind.google',
    docsUrl: 'deep-mind',
    fullTitle: 'DeepMind (Google)',
    group: 'provider',
    id: 'DeepMind',
    title: 'DeepMind',
  },
  {
    color: '#4D6BFE',
    desc: 'https://www.deepseek.com',
    docsUrl: 'deep-seek',
    fullTitle: 'DeepSeek',
    group: 'model',
    id: 'DeepSeek',
    title: 'DeepSeek',
  },
  {
    color: '#FFF',
    desc: 'https://team.doubao.com',
    docsUrl: 'doubao',
    fullTitle: 'Doubao (豆包)',
    group: 'model',
    id: 'Doubao',
    title: 'Doubao',
  },
  {
    color: '#000',
    desc: 'https://fireworks.ai',
    docsUrl: 'fireworks',
    fullTitle: 'Fireworks',
    group: 'provider',
    id: 'Fireworks',
    title: 'Fireworks',
  },
  {
    color: '#fff',
    desc: 'https://github.com/fishaudio',
    docsUrl: 'fish-audio',
    fullTitle: 'FishAudio (Bert)',
    group: 'model',
    id: 'FishAudio',
    title: 'FishAudio',
  },
  {
    color: '#fff',
    desc: 'https://blackforestlabs.ai/#get-flux',
    docsUrl: 'flux',
    fullTitle: 'Flux (black forest labs)',
    group: 'model',
    id: 'Flux',
    title: 'Flux',
  },
  {
    color: '#1C69FF',
    desc: 'https://deepmind.google/technologies/gemini',
    docsUrl: 'gemini',
    fullTitle: 'Gemini (Google)',
    group: 'model',
    id: 'Gemini',
    title: 'Gemini',
  },
  {
    color: '#2E96FF',
    desc: 'https://ai.google.dev/gemma',
    docsUrl: 'gemma',
    fullTitle: 'Gemma (Google)',
    group: 'model',
    id: 'Gemma',
    title: 'Gemma',
  },
  {
    color: '#000',
    desc: 'https://ai-assets.gitee.com/',
    docsUrl: 'gitee-ai',
    fullTitle: 'GiteeAI',
    group: 'provider',
    id: 'GiteeAI',
    title: 'GiteeAI',
  },
  {
    color: '#000',
    desc: 'https://github.com',
    docsUrl: 'github',
    fullTitle: 'Github',
    group: 'provider',
    id: 'Github',
    title: 'Github',
  },
  {
    color: '#000',
    desc: 'https://github.com/features/copilot',
    docsUrl: 'github-copilot',
    fullTitle: 'Github Copilot',
    group: 'application',
    id: 'GithubCopilot',
    title: 'GithubCopilot',
  },
  {
    color: '#fff',
    desc: 'https://google.com',
    docsUrl: 'google',
    fullTitle: 'Google',
    group: 'provider',
    id: 'Google',
    title: 'Google',
  },
  {
    color: '#fff',
    desc: 'https://grok.x.ai',
    docsUrl: 'grok',
    fullTitle: 'Grok (xAI)',
    group: 'model',
    id: 'Grok',
    title: 'Grok',
  },
  {
    color: '#F55036',
    desc: 'https://wow.groq.com',
    docsUrl: 'groq',
    fullTitle: 'Groq',
    group: 'provider',
    id: 'Groq',
    title: 'Groq',
  },
  {
    color: '#3E5CF4',
    desc: 'https://higress.cn/',
    docsUrl: 'higress',
    fullTitle: 'Higress',
    group: 'provider',
    id: 'Higress',
    title: 'Higress',
  },
  {
    color: '#fff',
    desc: 'https://huggingface.co',
    docsUrl: 'hugging-face',
    fullTitle: 'HuggingFace',
    group: 'provider',
    id: 'HuggingFace',
    title: 'HuggingFace',
  },
  {
    color: '#0053e0',
    desc: 'https://hunyuan.tencent.com',
    docsUrl: 'hunyuan',
    fullTitle: 'Hunyuan (腾讯混元)',
    group: 'model',
    id: 'Hunyuan',
    title: 'Hunyuan',
  },
  {
    color: '#1B3882',
    desc: 'https://internlm.intern-ai.org.cn',
    docsUrl: 'intern-lm',
    fullTitle: 'InternLM',
    group: 'provider',
    id: 'InternLM',
    title: 'InternLM',
  },
  {
    color: '#000',
    desc: 'https://klingai.com',
    docsUrl: 'kling',
    fullTitle: 'Kling (可灵)',
    group: 'application',
    id: 'Kling',
    title: 'Kling',
  },
  {
    color: '#CB2D30',
    desc: 'https://github.com/haotian-liu/LLaVA',
    docsUrl: 'l-la-va',
    fullTitle: 'LLaVA',
    group: 'model',
    id: 'LLaVA',
    title: 'LLaVA',
  },
  {
    color: '#000',
    desc: 'https://langfuse.com',
    docsUrl: 'langfuse',
    fullTitle: 'Langfuse',
    group: 'application',
    id: 'Langfuse',
    title: 'Langfuse',
  },
  {
    color: '#4338CA',
    desc: 'https://lmstudio.ai',
    docsUrl: 'lm-studio',
    fullTitle: 'LM Studio',
    group: 'provider',
    id: 'LmStudio',
    title: 'LM Studio',
  },
  {
    color: '#fff',
    desc: 'https://lobehub.com',
    docsUrl: 'lobe-hub',
    fullTitle: 'LobeHub',
    group: 'provider',
    id: 'LobeHub',
    title: 'LobeHub',
  },
  {
    color: '#000',
    desc: 'https://lumalabs.ai',
    docsUrl: 'luma',
    fullTitle: 'Luma',
    group: 'application',
    id: 'Luma',
    title: 'Luma',
  },
  {
    color: '#fff',
    desc: 'https://magic.dev',
    docsUrl: 'magic',
    fullTitle: 'Magic',
    group: 'model',
    id: 'Magic',
    title: 'Magic',
  },
  {
    color: '#1d65c1',
    desc: 'https://llama.meta.com',
    docsUrl: 'meta',
    fullTitle: 'Meta',
    group: 'provider',
    id: 'Meta',
    title: 'Meta',
  },
  {
    color: '#fff',
    desc: 'https://midjourney.com',
    docsUrl: 'midjourney',
    fullTitle: 'Midjourney',
    group: 'application',
    id: 'Midjourney',
    title: 'Midjourney',
  },
  {
    color: '#F23F5D',
    desc: 'https://api.minimax.chat',
    docsUrl: 'minimax',
    fullTitle: 'Minimax',
    group: 'model',
    id: 'Minimax',
    title: 'Minimax',
  },
  {
    color: '#fd6f00',
    desc: 'https://mistral.ai',
    docsUrl: 'mistral',
    fullTitle: 'Mistral',
    group: 'model',
    id: 'Mistral',
    title: 'Mistral',
  },
  {
    color: '#16191E',
    desc: 'https://moonshot.cn',
    docsUrl: 'moonshot',
    fullTitle: 'Moonshot (月之暗面)',
    group: 'provider',
    id: 'Moonshot',
    title: 'MoonshotAI',
  },
  {
    color: '#6847f5',
    desc: 'https://novita.ai/',
    docsUrl: 'novita',
    fullTitle: 'Novita',
    group: 'provider',
    id: 'Novita',
    title: 'novita.ai',
  },
  {
    color: '#74B71B',
    desc: 'https://www.nvidia.com/en-us/ai-on-rtx/chat-with-rtx-generative-ai/',
    docsUrl: 'nvidia',
    fullTitle: 'Nvidia (ChatWithRTX)',
    group: 'application',
    id: 'Nvidia',
    title: 'Nvidia',
  },
  {
    color: '#fff',
    desc: 'https://ollama.ai',
    docsUrl: 'ollama',
    fullTitle: 'Ollama',
    group: 'provider',
    id: 'Ollama',
    title: 'Ollama',
  },
  {
    color: '#000',
    desc: 'https://openai.com',
    docsUrl: 'open-ai',
    fullTitle: 'OpenAI (ChatGPT)',
    group: 'provider',
    id: 'OpenAI',
    title: 'OpenAI',
  },
  {
    color: '#4A7FE3',
    desc: 'https://huggingface.co/openchat',
    docsUrl: 'open-chat',
    fullTitle: 'OpenChat',
    group: 'model',
    id: 'OpenChat',
    title: 'OpenChat',
  },
  {
    color: '#6566F1',
    desc: 'https://openrouter.ai',
    docsUrl: 'open-router',
    fullTitle: 'OpenRouter',
    group: 'provider',
    id: 'OpenRouter',
    title: 'OpenRouter',
  },
  {
    color: '#FFF',
    desc: 'https://ai.google/discover/palm2',
    docsUrl: 'pa-lm',
    fullTitle: 'PaLM (Google)',
    group: 'model',
    id: 'PaLM',
    title: 'PaLM',
  },
  {
    color: '#22B8CD',
    desc: 'https://perplexity.ai',
    docsUrl: 'perplexity',
    fullTitle: 'Perplexity',
    group: 'provider',
    id: 'Perplexity',
    title: 'Perplexity',
  },
  {
    color: '#000',
    desc: 'https://pollinations.ai',
    docsUrl: 'pollinations',
    fullTitle: 'Pollinations',
    group: 'application',
    id: 'Pollinations',
    title: 'Pollinations',
  },
  {
    color: '#1041F3',
    desc: 'https://chatglm.cn',
    docsUrl: 'qingyan',
    fullTitle: 'Qingyan (智谱清言)',
    group: 'application',
    id: 'Qingyan',
    title: 'Qingyan',
  },
  {
    color: '#615ced',
    desc: 'https://huggingface.co/Qwen',
    docsUrl: 'qwen',
    fullTitle: 'Qwen (千问)',
    group: 'model',
    id: 'Qwen',
    title: 'Qwen',
  },
  {
    color: '#EA2805',
    desc: 'https://replicate.com',
    docsUrl: 'replicate',
    fullTitle: 'Replicate',
    group: 'provider',
    id: 'Replicate',
    title: 'Replicate',
  },
  {
    color: '#fff',
    desc: 'https://runwayml.com',
    docsUrl: 'runway',
    fullTitle: 'Runway',
    group: 'application',
    id: 'Runway',
    title: 'Runway',
  },
  {
    color: '#3431C3',
    desc: 'https://github.com/RWKV',
    docsUrl: 'rwkv',
    fullTitle: 'RWKV',
    group: 'model',
    id: 'Rwkv',
    title: 'RWKV',
  },
  {
    color: '#5B2AD8',
    desc: 'https://platform.sensenova.cn',
    docsUrl: 'sense-nova',
    fullTitle: 'SenseNova',
    group: 'provider',
    id: 'SenseNova',
    title: 'SenseNova',
  },
  {
    color: '#7C3AED',
    desc: 'https://siliconflow.cn/zh-cn/',
    docsUrl: 'silicon-cloud',
    fullTitle: 'SiliconCloud (SiliconFlow)',
    group: 'provider',
    id: 'SiliconCloud',
    title: 'SiliconCloud',
  },
  {
    color: '#0070f0',
    desc: 'https://xinghuo.xfyun.cn',
    docsUrl: 'spark',
    fullTitle: 'Spark (讯飞星火)',
    group: 'model',
    id: 'Spark',
    title: 'Spark',
  },
  {
    color: '#330066',
    desc: 'https://deepmind.google/technologies/gemini',
    docsUrl: 'stability',
    fullTitle: 'Stability (StableDiffusion)',
    group: 'provider',
    id: 'Stability',
    title: 'Stability',
  },
  {
    color: '#005AFF',
    desc: 'https://www.stepfun.com',
    docsUrl: 'stepfun',
    fullTitle: 'Stepfun (阶跃星辰)',
    group: 'model',
    id: 'Stepfun',
    title: 'Stepfun',
  },
  {
    color: '#000',
    desc: 'https://app.suno.ai',
    docsUrl: 'suno',
    fullTitle: 'Suno',
    group: 'application',
    id: 'Suno',
    title: 'Suno',
  },
  {
    color: '#0052D9',
    desc: 'https://tencent.com',
    docsUrl: 'tencent',
    fullTitle: 'Tencent',
    group: 'provider',
    id: 'Tencent',
    title: 'Tencent',
  },
  {
    color: '#0f6fff',
    desc: 'https://www.together.ai',
    docsUrl: 'together',
    fullTitle: 'together.ai',
    group: 'provider',
    id: 'Together',
    title: 'together.ai',
  },
  {
    color: '#908AF9',
    desc: 'https://www.upstage.ai',
    docsUrl: 'upstage',
    fullTitle: 'Upstage',
    group: 'provider',
    id: 'Upstage',
    title: 'Upsate',
  },
  {
    color: '#4285F4',
    desc: 'https://cloud.google.com/generative-ai-studio',
    docsUrl: 'vertex-ai',
    fullTitle: 'VertexAI (Google)',
    group: 'provider',
    id: 'VertexAI',
    title: 'VertexAI',
  },
  {
    color: '#000',
    desc: 'https://viggle.ai',
    docsUrl: 'viggle',
    fullTitle: 'Viggle',
    group: 'application',
    id: 'Viggle',
    title: 'Viggle',
  },
  {
    color: '#fff',
    desc: 'https://github.com/vllm-project',
    docsUrl: 'vllm',
    fullTitle: 'vLLM',
    group: 'provider',
    id: 'Vllm',
    title: 'vLLM',
  },
  {
    color: '#167ADF',
    desc: 'https://yiyan.baidu.com',
    docsUrl: 'wenxin',
    fullTitle: 'Wenxin (文心)',
    group: 'model',
    id: 'Wenxin',
    title: 'Wenxin',
  },
  {
    color: '#F38020',
    desc: 'https://developers.cloudflare.com/workers-ai',
    docsUrl: 'workers-ai',
    fullTitle: 'WorkersAI (Cloudflare)',
    group: 'provider',
    id: 'WorkersAI',
    title: 'WorkersAI',
  },
  {
    color: '#fff',
    desc: 'https://x.ai',
    docsUrl: 'xai',
    fullTitle: 'xAI',
    group: 'provider',
    id: 'XAI',
    title: 'Grok',
  },
  {
    color: '#003425',
    desc: 'https://github.com/01-ai/Yi',
    docsUrl: 'yi',
    fullTitle: 'Yi (零一万物)',
    group: 'model',
    id: 'Yi',
    title: 'Yi',
  },
  {
    color: '#6300FF',
    desc: 'https://zeabur.com',
    docsUrl: 'zeabur',
    fullTitle: 'Zeabur',
    group: 'application',
    id: 'Zeabur',
    title: 'Zeabur',
  },
  {
    color: '#003425',
    desc: 'https://www.lingyiwanwu.com/',
    docsUrl: 'zero-one',
    fullTitle: '01.AI (零一万物)',
    group: 'provider',
    id: 'ZeroOne',
    title: '01.AI',
  },
  {
    color: '#3859FF',
    desc: 'https://zhipuai.cn',
    docsUrl: 'zhipu',
    fullTitle: 'Zhipu (智谱)',
    group: 'provider',
    id: 'Zhipu',
    title: 'Zhipu',
  },
];

export default toc;
